### ISSUE TITLE
Theme Color not set properly

### ISSUE THREAD

**Issue by davidatkinswwt** [dryven/faviconator#1]
Thank you for putting this add-on together. It's worked very well for several projects. 😁

I'm only just now noticing the theme color is not being saved and/or used properly in the template.

I went and looked at the other projects and the meta tags are defaulting to #ffffff as well.

Thanks again!

Should probably mention I'm using
- Statamic 3.3.63
- PHP 8.2

![CleanShot 2022-12-28 at 12 39 15@2x](https://user-images.githubusercontent.com/28378640/209858243-6b9f4421-0408-4bbd-b5a1-d64cef307b3f.png)

**Comment by dryven-dano** [comment]
Hey David!

I'm glad to hear that you like the addon 😄 Thank you for noticing and reporting the bug. I just released a new patch version that fixes the small mishap. Hope you have a great day and build awesome websites!

Cheers,
Dano.
